### ISSUE TITLE
这个项目克隆到本地，跑不起来啊

### ISSUE THREAD

**Issue by wx-wangxiang** [GaryChangCN/zhihu-daily-byVuejs#1]
我通过命令行在app.js的根目录下，执行了node app.js,然后在浏览器里面访问localhost:8088，浏览器报错，访问不了。然后我看了源码，也没找到首页的路由，作者能说说，首页的路由在哪？而且我webpack打包也出错了

**Comment by wx-wangxiang** [comment]
我后来自己又看了，发现是你在vue单文件组件的template中的img标签里引用的图片地址有问题，loader识别不了，我在dist目录下也没有找到相应的图片文件

**Comment by GaryChangCN** [comment]
dist目录内有个logo图片应该 你自己添加一个  另外这是vue 1.0版本

**Comment by wx-wangxiang** [comment]
你这个demo为什么会有两种启动的方式，在首页的readme里面是：
node app.js
npm install
npm start
在zhihu-daily-byVuejs这个目录下的readme里面又是这样的：
npm install
npm run dev
npm run build
到底是怎么启动这个demo的，作者能说清楚吗？

**Comment by GaryChangCN** [comment]
run build 是生产代码
run dev是开发环境
另外server文件夹下旭单独启动来爬外链图片
以及需要nginx反向代理

**Comment by cookingHero** [comment]
你的服务访问的话报错啦，想根据您这个学习下，有时间帮忙看下！！

**Comment by GaryChangCN** [comment]
@cookingHero 服务器到期了，后端没了，你可以本地启动 server，
